Repository intive/patronage22_poznan_mobile, pull requests merged in 2022-03, with the labels that each got.

#23 P2022 1320 register screen/create layout
  app/src/main/java/com/intive/patronage22/intivi/Fragments/SignInFragment.kt
  app/src/main/java/com/intive/patronage22/intivi/Fragments/SignUpFragment.kt
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: waiting_for_another_PR_merge

#26 P2022-1291/Creates footer bar in MainActivity with three tabs.
  app/src/main/res/drawable/ic_genres.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/sh_tab_indicator.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ready_to_merge

#30 P2022-1322 [Reset Password] / Show/hide password:
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/intive/patronage22/intivi/ResetPasswordActivity.kt
  app/src/main/res/drawable/bottom_button_background.xml
  app/src/main/res/drawable/ic_chevron_left_stroke.xml
  app/src/main/res/drawable/ic_hide_password.xml
  app/src/main/res/drawable/ic_show_password.xml
  app/src/main/res/font/inter_medium.ttf
  app/src/main/res/layout/activity_details.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ready_to_merge

#51 P2022 1754/view model
  app/build.gradle
  app/src/main/java/com/intive/patronage22/intivi/Fragments/SignInFragment.kt
  app/src/main/java/com/intive/patronage22/intivi/Fragments/SignUpFragment.kt
  app/src/main/java/com/intive/patronage22/intivi/OnTextChangeListener.kt
  app/src/main/java/com/intive/patronage22/intivi/ViewModels/LoginViewModel.kt
  app/src/main/res/layout/fragment_sign_in.xml
Labels: additional_task
